name: SimpleMail
main: me.odium.test.simplemail
version: 0.3.8
commands:
   mail:
      aliases: [simplemail]
      description: Display Help Menu
      permission: SimpleMail.inbox
      usage: /mail
   sendmail:
      description: Send mail to a user
      permission: SimpleMail.sendmail
      usage: /sendmail <player> <message>
   inbox:
      description: View your inbox
      permission: SimpleMail.inbox
      usage: /inbox
   outbox:
      description: View your outbox
      permission: SimpleMail.outbox
      usage: /outbox
   readmail:
      description: Read a message
      permission: SimpleMail.inbox
      usage: /readmail <id>
   delmail:
      description: delete a message
      permission: SimpleMail.inbox
      usage: /delmail <id>
   mailboxes:
      description: view active mailboxes
      permission: SimpleMail.admin
      usage: /mailboxes
   clearmailbox:
      description: clear an active mailbox
      permission: SimpleMail.admin
      usage: /clearmailbox <player>
   purgemail:
      description: Purge expired messages rom database
      permission: SimpleMail.admin
      usage: /purgemail